responsiveweb/urls.py
from django.urls import path
from . import views

app_name= 'responsiveweb'

urlpatterns = [
    path('', views.Homepage, name='Homepage'),
    path('About/', views.About, name='About'),
    path('Gallery/', views.Gallery, name='Gallery'),
    
    path('Schedule/', views.schedule, name="schedule"),
	path('Showschedule/', views.showschedule, name="showschedule"),
	path('delete/', views.delete, name="delete"),

    
    

]

story/urls.py
from django.urls import path, include, re_path
from django.contrib import admin




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('responsiveweb.urls')),
    
    
]

responsiveweb/models.py
from django.db import models

class Schedule(models.Model):
	
	day = models.CharField(max_length=10)
	date = models.DateField()
	time = models.TimeField()
	name = models.CharField(max_length=30)
	location = models.CharField(max_length=30)
	category = models.CharField(max_length=20)


# Create your models here.

responsiveweb/forms.py
from django import forms
from .models import Schedule

class ActivitySchedule(forms.Form):
	day = forms.CharField(label="Day", max_length=20)
	date = forms.DateField(widget=forms.DateInput(attrs={'type' : 'date'}))
	time = forms.TimeField(widget=forms.TimeInput(attrs={'type' : 'time'}))
	name = forms.CharField(label="Activity Name", max_length=30, required=True)
	location = forms.CharField(label="Location", max_length=30)
	category = forms.CharField(label="Category", max_length=30)

responsiveweb/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.template import Context, loader
from django.utils import timezone
import datetime
from .models import Schedule
from .forms import ActivitySchedule

# Create your views here.
def Homepage(request):
    return render(request, 'Homepage.html')
def About(request):
    return render(request, 'About.html')
def Gallery(request):
    return render(request, 'Gallery.html')


def schedule(request):
	form = ActivitySchedule(request.POST or None)
	response = {}
	if(request.method == "POST"):
		if (form.is_valid()):
			day = request.POST.get("day")
			date = request.POST.get("date")
			time = request.POST.get("time")
			name = request.POST.get("name")
			location = request.POST.get("location")
			category = request.POST.get("category")
			Schedule.objects.create(day=day, date=date, time=time, name=name, location=location, category=category)
			return redirect('/Showschedule')
		else:
			response['form'] = form
			return render(request, 'schedule.html', response)
	else:
		response['form'] = form
		return render(request, 'schedule.html', response)


def showschedule(request):
    response = {}
    schedule = Schedule.objects.all()
    response = {
        "schedule" : schedule
    }
    return render(request, 'showschedule.html', response)


def delete(request):
    schedule = Schedule.objects.all().delete()
    return redirect('/Showschedule')


# Create your views here.

responsiveweb/templates/About.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Responsive Page</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Muli:800|Permanent+Marker|Work+Sans:800|Montserrat:400,500&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/gallery.css' %}">
    </head>

    <body class="about">
        <!-- TEST UBAH -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light navv" style="background: rgba(196, 196, 196, 0.7);">
            <a class="navbar-brand brand" href="{% url 'responsiveweb:Homepage' %}">Kukuh Hafiyyan</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <div class="navbar-nav ml-auto">
                        <li>  <a class="About" href="{% url 'responsiveweb:About' %}">About</a> </li>
                        <li>  <a class="Gallery" href="{% url 'responsiveweb:Gallery' %}">Gallery</a> </li>
                        <li>  <a class="Experience" href="{% url 'responsiveweb:schedule' %}">Form</a> </li>
                        <li>  <a class="Skills" href="{% url 'responsiveweb:showschedule' %}">Schedule</a> </li>> </li>
    
                </div>
            </div>
        </nav>

        <div class="container conB">
            <div class="row rowAbout">
                <div class="col-lg-4    A-col">
                    <img src="{% static 'images/kkukuh.png'%}" class="img-fluid" alt="">
                </div>
                <div class="col-lg-4">
                    <p class="nama">Kukuh Hafiyyan</p>
                    <p class="work">IT Student</p>
                    <p class="desc">I like to try something new and accept challanges in purpose to make myself better. I am a hard worker person and also a consistent individual.</p>
                </div>
                <div class="col-lg-4">
                    <p class="title">
                        <br>Name      : Kukuh Hafiyyan
                        <br>Birthday  : March 13, 2000
                        <br>Address   : Jakarta, Indonesia
                        <br>Email     : kukuh.hafiyyan@ui.ac.id
                        <br>Phone     : 08119132000
                        <br>University: Universitas Indonesia
                    </p>
                </div>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

responsiveweb/templates/Gallery.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Responsive Page</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Muli:800|Permanent+Marker|Work+Sans:800|Montserrat:400,500&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/gallery.css' %}">
    </head>

    <body class="Gall">
        <nav class="navbar navbar-expand-lg navbar-light bg-light navv" style="background: rgba(196, 196, 196, 0.7);">
            <a class="navbar-brand brand" href="{% url 'responsiveweb:Homepage' %}">Kukuh Hafiyyan</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <div class="navbar-nav ml-auto">
                        <li>  <a class="About" href="{% url 'responsiveweb:About' %}">About</a> </li>
                        <li>  <a class="Gallery" href="{% url 'responsiveweb:Gallery' %}">Gallery</a> </li>
                        <li>  <a class="Experience" href="{% url 'responsiveweb:schedule' %}">Form</a> </li>
                        <li>  <a class="Skills" href="{% url 'responsiveweb:showschedule' %}">Schedule</a> </li>
    
                </div>
            </div>
        </nav>
        
        <img src="{% static 'images/Gallery.png' %}" class="img-fluid text-center" alt="Responsive Image">
        
        <div class="container">
            <div class="row g-row">
            
            </div>
            <div class="row g-row1">
                <div class="col-lg-3 col-md-6 col-sm-6 g-col first"><img src="{% static 'images/GWK.png'%}" alt=""></div>
                <div class="col-lg-3 col-md-6 col-sm-6 g-col second"><img src="{% static 'images/MLY.png'%}" alt=""></div>
                <div class="col-lg-3 col-md-6 col-sm-6 g-col third"><img src="{% static 'images/GBK.png'%}" alt=""></div>
                <div class="col-lg-3 col-md-6 col-sm-6 g-col fourth"><img src="{% static 'images/BDG.png'%}" alt=""></div>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

responsiveweb/templates/Homepage.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Responsive Page</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Muli:800|Permanent+Marker|Work+Sans:800|Montserrat:400,500&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/gallery.css' %}">
    </head>

    <body class="Home">
        <nav class="navbar navbar-expand-lg navbar-light bg-light navv" style="background: rgba(196, 196, 196, 0.7);">
            <a class="navbar-brand brand" href="{% url 'responsiveweb:Homepage' %}">Kukuh Hafiyyan</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <div class="navbar-nav ml-auto">
                <li>  <a class="About" href="{% url 'responsiveweb:About' %}">About</a> </li>
                <li>  <a class="Gallery" href="{% url 'responsiveweb:Gallery' %}">Gallery</a> </li>
                <li>  <a class="Experience" href="{% url 'responsiveweb:schedule' %}">Form</a> </li>
                <li>  <a class="Skills" href="{% url 'responsiveweb:showschedule' %}">Schedule</a> </li>
    
                </div>
            </div>
        </nav>
        <div class="row homerow">
                
            <img src="{% static 'images/labelhome.png' %}" class="img-fluid" alt="Responsive Image"> 
            <div class="col-lg-4 col-md-12 col-sm-12 col-12 colhom">
                <img src="{% static 'images/Layer 5.png' %}" class="img-fluid" style="box-shadow: 10px 10px 100px #000000;" alt="Responsive Image">
            </div>
            <div class="col-lg-7 col-md-12 col-sm-12 col-12 colhom">
                <p class="welcome" style="z-index: 3">Welcome</p>
                <p class="welcomeb" style="z-index: 2">Welcome</p>
                <p class="tomy" style="z-index: 3">To My Page !</p>
                <p class="tomyb" style="z-index: 2">To My Page !</p>
                
            </div>
            <div class="col-lg-1 col-md-12 col-sm-12 col-12">
                
            </div>   
        </div>
        
        
        
        
        
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    </body>
</html>

responsiveweb/templates/schedule.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Form Page</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Muli:800|Permanent+Marker|Work+Sans:800|Montserrat:400,500&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/gallery.css' %}">
    </head>

    <body class="exp">
        <nav class="navbar navbar-expand-lg navbar-light bg-light navv" style="background: rgba(196, 196, 196, 0.7);">
            <a class="navbar-brand brand" href="{% url 'responsiveweb:Homepage' %}">Kukuh Hafiyyan</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <div class="navbar-nav ml-auto">
                        <li>  <a class="About" href="{% url 'responsiveweb:About' %}">About</a> </li>
                        <li>  <a class="Gallery" href="{% url 'responsiveweb:Gallery' %}">Gallery</a> </li>
                        <li>  <a class="Experience" href="{% url 'responsiveweb:schedule' %}">Form</a> </li>
                        <li>  <a class="Skills" href="{% url 'responsiveweb:showschedule' %}">Schedule</a> </li>
    
                </div>
            </div>
        </nav>

        <img src="{% static 'images/SCHEDULE.png' %}" class="img-fluid text-center" alt="Responsive Image">
        
        <div class="container-fluid p-5">
            <h3>Create Schedule</h3>
            <div id="ski" class="rectangle"></div>
            <hr>
            <form class="col-lg-12", method="POST", action="{% url 'responsiveweb:schedule' %}">
                {% csrf_token %}
                <div class="fields">
                {% for field in form %}      
                    <p>{{ field.label_tag }} {{ field }}</p>
                {% endfor %}
                </div>
                <button type="submit" class="button btn">Submit</button>
            </form>
        </div>
    
    
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

responsiveweb/templates/showschedule.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Schedule</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Muli:800|Permanent+Marker|Work+Sans:800|Montserrat:400,500&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/gallery.css' %}">
    </head>
    <body class="skil">
            
        <nav class="navbar navbar-expand-lg navbar-light bg-light navv" style="background: rgba(196, 196, 196, 0.7);">
            <a class="navbar-brand brand" href="{% url 'responsiveweb:Homepage' %}">Kukuh Hafiyyan</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <div class="navbar-nav ml-auto">
                <li>  <a class="About" href="{% url 'responsiveweb:About' %}">About</a> </li>
                <li>  <a class="Gallery" href="{% url 'responsiveweb:Gallery' %}">Gallery</a> </li>
                <li>  <a class="Experience" href="{% url 'responsiveweb:schedule' %}">Form</a> </li>
                <li>  <a class="Skills" href="{% url 'responsiveweb:showschedule' %}">Schedule</a> </li>
    
                </div>
            </div>
        </nav>
        
        <img src="{% static 'images/SCHEDULE.png' %}" class="img-fluid text-center" alt="Responsive Image">
        
        <div class="container-fluid col-lg-12 p-5">
            <h3>Schedule</h3>
            <div id="edu" class="rectangle"></div>
            <hr>
            <table style="width: 100%">
            {% if schedule %}
                <tr class="">
                    <th>Activity</th>
                    <th>Day / Date</th>
                    <th>Time</th>
                    <th>Location</th>
                    <th>Category</th>
                </tr>
                {% for schedule in schedule %}
                    <tr>
                        <td>{{ schedule.name }}</td>
                        <td>{{ schedule.day }} / {{ schedule.date }}</td> 
                        <td>{{ schedule.time }}</td>
                        <td>{{ schedule.location }}</td>
                        <td>{{ schedule.category }}</td>
                    </tr>
                {% endfor %}
                {% else %}
                    <h5 class="red">There are no upcoming events yet!</h5> 
                {% endif %}
        </table>
        <br>
            <div class="d-flex align-items-center justify-content-center">
                <a href="{% url 'responsiveweb:schedule' %}">Create Schedule</a>
                <a href="{% url 'responsiveweb:delete' %}">Delete All</a>
            </div>
        </div>
    
    

            
        
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>